{% set name = "vllm" %}
{% set version = "0.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vllm-{{ version }}.tar.gz
  sha256: c7e04d1046304397b4580334038b558fe491af155fdea508224f140172cf9a82

build:
  skip: true  # [py>=313 or py2k]
  entry_points:
    - vllm = vllm.entrypoints.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - cmake
    - ninja
    - packaging
    - setuptools 
    - setuptools-scm
      #- pytorch ==2.6.0
    - wheel
    - jinja2
    - pip
  run:
    - python >=3.9,<3.13
    - cachetools
    - psutil
    - sentencepiece
    - numpy
    - requests
    - tqdm
    - blake3
    - py-cpuinfo
    - transformers
    - huggingface_hub
    - tokenizers
    - protobuf
    - fastapi
    - aiohttp
    - openai
    - pydantic
    - prometheus_client
    - pillow
    - prometheus-fastapi-instrumentator
    - tiktoken 
    - lm-format-enforcer
    - llguidance 
    - outlines 
    - lark
    - xgrammar
    - typing_extensions
    - filelock
    - partial-json-parser
    - pyzmq 
    - msgspec
    - gguf 
    - importlib-metadata
    - mistral-common
    - opencv
    - pyyaml
    - six >=1.16.0  # [py>311]
    - setuptools >=74.1.1  # [py>311]
    - einops
    - compressed-tensors
    - depyf 
    - cloudpickle
    - watchfiles
    - python-json-logger
    - scipy
    - ninja
    - opentelemetry-sdk 
    - opentelemetry-api
    - opentelemetry-exporter-otlp
    - opentelemetry-semantic-conventions-ai
    - numba ==0.60.0  # [py==39]
    - ray !=2.44.*,>=2.43.0
      #- pytorch ==2.6.0
    - torchaudio
    - torchvision
    - xformers   # [linux]

test:
  imports:
    - vllm
  commands:
    - pip check
    - vllm --help
  requires:
    - pip

about:
  summary: A high-throughput and memory-efficient inference and serving engine for LLMs
  license: Apache-2.0
  license_file:
    - LICENSE
    - csrc/quantization/marlin/sparse/LICENSE
    - csrc/quantization/marlin/dense/LICENSE

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Client request
  recipe-maintainers:
    - ianaobi
    - bkreider
